# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CombineNetworking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'STTwitter'
  pod 'LBTATools'
  pod 'SDWebImage'
  # Pods for CombineNetworking

end
